### ISSUE TITLE
Changing the States of Tasks and Projects

### ISSUE THREAD

**Issue by basketingballs** [solidtime-io/solidtime#114]
Hello there, i was wondering if there is already a way to change the states of tasks and projects, i used the webapp for a while and couldn't find it, if it is there then it is sure not apparent.
Looks like a promising project so keep it going guys!

**Comment by Sukaato** [comment]
Same here, creating a task is nice, but after i finished it i want to "close" it

**Comment by korridor** [comment]
Thanks for the suggestion! :) We are currently working on features that will make it possible to mark tasks as done and archive projects. Is that what you meant with your suggestion?

If you are interested, you can watch the progress of the feature development in this PR: https://github.com/solidtime-io/solidtime/pull/110 (naming of the PR could be better)

**Comment by Onatcer** [comment]
States for tasks (done) and projects (archived) are now merged in the main branch. If there are any more questions or requests about this feature please open a new issue.
