### ISSUE TITLE
Sidebar overlaps main content when scrolling in a smaller window

### ISSUE THREAD

**Issue by M-Barrows** [solidtime-io/solidtime#123]
When my window is 700px wide, there is not enough space to show all content on the screen. This is fine but when I scroll over to see the rest of it, the sidebar has some odd interactions with the main content. In the image below, take note of the play button for the current task, highlighting of the current page (Projects), the label text for other pages, and the black sidebar background. 

![image](https://github.com/solidtime-io/solidtime/assets/7907749/6972e9bf-c524-4bab-8012-01a70d62a474)

**Comment by korridor** [comment]
Thanks for the report, we'll look into this.

**Comment by Onatcer** [comment]
I'm pretty sure this is fixed in the current version; I changed the breakpoints at some point. If this issue persists, feel free to comment again or open a new issue.
