### ISSUE TITLE
Uploaded Image not shown after upload

### ISSUE THREAD

**Issue by thelooter** [solidtime-io/solidtime#128]
I tried to upload a profile Picture to my account, but it just shows this
![image](https://github.com/solidtime-io/solidtime/assets/24987877/66387666-b3fc-4837-8123-2718c7d1957a)
![image](https://github.com/solidtime-io/solidtime/assets/24987877/44bfb51d-8df6-4d90-bd47-6c9074ee633a)

Immediately after uploading, it shows the image correctly in the settings page, after that it fails
![image](https://github.com/solidtime-io/solidtime/assets/24987877/58ed3eee-ec3d-46f2-8cae-1605b160bf89)

This is the uploaded image
https://avatars.githubusercontent.com/u/24987877?v=4

**Comment by korridor** [comment]
Could you please provide me with additional information about your file storage setup? (https://docs.solidtime.io/self-hosting/configuration#file-storage) Which driver are you using?

Could you also show me where the application tries to load the image from? You can probably see that in the network console. If this is sensitive information, you can send me this in a private message on Discord.

**Comment by gungun974** [comment]
I personally occurred the same issue but I remember that by default laravel don't create the public link of storage.

I did `php artisan storage:link` and now octane can access the public directory.

**Comment by korridor** [comment]
@gungun974 Thanks for your message! You are right, if you want to use the local storage provider, you need to run `php artisan storage:link`. This was part of the old Docker image, but I forgot to add this to the new one as well.

I just fixed that in the `main` branch in the following commit: https://github.com/solidtime-io/solidtime/commit/ba07616111f56961f3d448e8572c867ac50e879c

This will be part of the next release. Until then, @thelooter, you can run `php artisan storage:link` manually.

**Comment by John-Bob-DIRIENZO** [comment]
Hello @korridor, I had the very same issue and running `php artisan storage:link` solved the issue. Thanks a lot
