### ISSUE TITLE
Cache Path Error

### ISSUE THREAD

**Issue by tquizzle** [solidtime-io/solidtime#169]
When trying to just start the scheduler for generate-keys, I am receiving the following:

```
In Compiler.php line 67:

  Please provide a valid cache path.
```

**Comment by korridor** [comment]
Could you provide us with additional information about your setup?

Also did you do the following things before running `artisan self-host:generate-keys`:
 - Create the environment file (Docs: https://docs.solidtime.io/self-hosting/guides/docker#2-the-environment-files)
 - Correct the permissions for the `app-storage` and `logs` folder (Docs: https://github.com/solidtime-io/self-hosting-examples/tree/main/0-docker-traefik-with-database#installation)

**Comment by memphisraynz** [comment]
I have followed along with the docs for solidtime+database and I am getting the same error

`2024-09-11 00:46:52] production.ERROR: Please provide a valid cache path. {"exception":"[object] (InvalidArgumentException(code: 0): Please provide a valid cache path. at /var/www/html/vendor/laravel/framework/src/Illuminate/View/Compilers/Compiler.php:67)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/View/ViewServiceProvider.php(97): Illuminate\\View\\Compilers\\Compiler->__construct()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(900): Illuminate\\View\\ViewServiceProvider->Illuminate\\View\\{closure}()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(787): Illuminate\\Container\\Container->build()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1041): Illuminate\\Container\\Container->resolve()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(723): Illuminate\\Foundation\\Application->resolve()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1026): Illuminate\\Container\\Container->make()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1446): Illuminate\\Foundation\\Application->make()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): Illuminate\\Container\\Container->offsetGet()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(208): Illuminate\\Support\\Facades\\Facade::resolveFacadeInstance()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(351): Illuminate\\Support\\Facades\\Facade::getFacadeRoot()
#10 /var/www/html/vendor/blade-ui-kit/blade-icons/src/BladeIconsServiceProvider.php(98): Illuminate\\Support\\Facades\\Facade::__callStatic()
#11 /var/www/html/vendor/blade-ui-kit/blade-icons/src/BladeIconsServiceProvider.php(27): BladeUI\\Icons\\BladeIconsServiceProvider->bootDirectives()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): BladeUI\\Icons\\BladeIconsServiceProvider->boot()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1114): Illuminate\\Container\\Container->call()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1095): Illuminate\\Foundation\\Application->bootProvider()
#19 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1094): array_walk()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(316): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(470): Illuminate\\Foundation\\Application->bootstrapWith()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(194): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#25 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#26 {main}
"} `

**Comment by korridor** [comment]
> Could you provide us with additional information about your setup?
> 
> Also did you do the following things before running `artisan self-host:generate-keys`:
> 
>   * Create the environment file (Docs: https://docs.solidtime.io/self-hosting/guides/docker#2-the-environment-files)
> 
>   * Correct the permissions for the `app-storage` and `logs` folder (Docs: https://github.com/solidtime-io/self-hosting-examples/tree/main/0-docker-traefik-with-database#installation)

@memphisraynz Thanks for the stack trace. Did you do the things I asked @tquizzle in the comment before yours?

**Comment by memphisraynz** [comment]
I sure can provide some more information. What other details would help you?

Yes, I performed the generate keys and the guide on the 2 separate .env
files

**Comment by korridor** [comment]
@memphisraynz Just to be safe, you also ran `chown -R 1000:1000 app-storage logs` before running `artisan self-host:generate-keys`?

If yes, please pull the latest version of the example repository. I fixed a few things, and it is possible that one of those changes also resolve your problem. ([Commit](https://github.com/solidtime-io/self-hosting-examples/commit/b4a1a6489ac445de7a8d699557543b80b81348ad))

If this does not resolve your issue, please write here again, and I'll inform you about the information I need to further debug the issue.

**Comment by whallin** [comment]
> It's not enough to create the `app-storage` and `logs` folders with the correct permissions, but apparently you also need `app-storage/framework/cache`. This fixes the issue for me.

@IHappyDayI mind sharing exactly which paths you're mounting from the container?

Unless you're literally just mapping "`/app-storage/framework/cache`" from the container to the host, it seems to be one of those "it works on my machine" situations.

**Comment by korridor** [comment]
@IHappyDayI I suspect that the folders don't have the correct file permission and that is why even though the folders have the correct owner, Laravel cannot create subfolders (which it needs to be able to do, not only for the `framework/cache` folder). 

Could you send me the output of the following commands:
```
ls -al /opt/solidtime/storage
ls -al /opt/solidtime/storage/app/framework
```

Furthermore, there is currently a separate issue with the ARM image. If you can run the queue and the scheduler without problems, but the app container is stuck in a restart loop, then you are having the same issue as I on ARM. I'm currently investigating. Please keep in mind that the ARM image is not officially released yet, which is why it is only in the `main` tag and not in the `latest` tag.

**Comment by memphisraynz** [comment]
I can see this got marked with a 'needs reproduction' tag.
What can I do to help diagnose this?

**Comment by korridor** [comment]
@IHappyDayI Sorry for the delayed response. Thank you for sending the `ls` outputs. The permissions of your folders are not correct (`1000` != `root`). If you follow our guide, the folder permissions should be correct. If you do your setup, please ensure that the PHP process can write in the folder relevant to running a Laravel application.

**Comment by korridor** [comment]
@memphisraynz Did you already do the things that I wrote you in this comment? https://github.com/solidtime-io/solidtime/issues/169#issuecomment-2349189628

**Comment by kdurek** [comment]
Just wanted to help anyone further, i was missing `chmod -R 775 app-storage`

**Comment by smileBeda** [comment]
This error is replicable when pulling up the container.
The docs do not say to create anything like `/opt/solidtime/storage`, they only mention `app-storage` and `logs`:
https://github.com/solidtime-io/self-hosting-examples/tree/main/1-docker-with-database#installation

when pulling up the docker, the logs will say:
```
sudo docker compose logs -f
scheduler-1  | Container mode: scheduler
scheduler-1  | [2025-09-30 14:03:16] production.ERROR: Please provide a valid cache path. {"exception":"[object] (InvalidArgumentException(code: 0): Please provide a valid cache path. at /var/www/html/vendor/laravel/framework/src/Illuminate/View/Compilers/Compiler.php:75)
scheduler-1  | [stacktrace]
scheduler-1  | #0 /var/www/html/vendor/laravel/framework/src/Illuminate/View/ViewServiceProvider.php(97): Illuminate\\View\\Compilers\\Compiler->__construct()
scheduler-1  | #1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1010): Illuminate\\View\\ViewServiceProvider->Illuminate\\View\\{closure}()
scheduler-1  | #2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(890): Illuminate\\Container\\Container->build()
scheduler-1  | #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1077): Illuminate\\Container\\Container->resolve()
scheduler-1  | #4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(821): Illuminate\\Foundation\\Application->resolve()
scheduler-1  | #5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1057): Illuminate\\Container\\Container->make()

```

This error will then repeat through all other containers, forever.
The reason, I think, is:
```
volumes:
      - "app-storage:/var/www/html/storage"
      - "./logs:/var/www/html/storage/logs"
      - "./app-storage:/var/www/html/storage/app"
```

So you end up with a Frankenstein: some parts come from a hidden Docker volume, others from your host. That’s why Laravel complains: things like storage/framework/views are missing because the base storage dir is swallowed by the first line.

The proper approach is to either use docker volume or host volume

In my case I chose host volume because it is more manageable and cleaner, but you have to manually add the folders, since the code does not check for it:
```
mkdir -p app-storage/app
mkdir -p app-storage/framework/{cache,sessions,views}
mkdir -p logs
```
(chown properly)
then
```
volumes:
  - ./app-storage:/var/www/html/storage
  - ./logs:/var/www/html/storage/logs
```

This needs to be corrected in the docker file, and ideally, it should create the subfolders on its own.

**Comment by 33Fraise33** [comment]
Hello,

I can confirm this issue is still present. On top of that it seems the 1000:1000 user is hardcoded in the build of the docker container so a user can not decide to map the container user to a different user on the host. 

I would love to take a single user business subscription but there are some things that do need improvement like the the above.
