### ISSUE TITLE
UI Create Client input field not cleared on success submit

### ISSUE THREAD

**Issue by ekafyi** [solidtime-io/solidtime#189]
Hi, I'm trying the cloud account and came across this minor UI issue. Nothing urgent, just thought I'd file this for the record.

**Environment:** Solidtime cloud

**Steps to reproduce:**
1. Go to [Clients list](https://app.solidtime.io/clients)
2. Click "+ Create Client" button, which will open a dialog modal
3. Type client name and hit Enter / click "Create Client". Dialog will close, new client will be added to the list.
4. Click "+ Create Client" button again to create another client 
5. Client name from step 3 is still displayed in the input field in the new dialog modal
   - Expectation: Input field is empty

It does not break any functionality, so it's more of a UX issue (user has to delete previous client name if adding more than 1 new clients).

I don't write Vue but I think `client.name` value should be reset here after `createClient`: https://github.com/solidtime-io/solidtime/blob/876a41cb2af65ab46dc9f092526a68c601a00d8c/resources/js/Components/Common/Client/ClientCreateModal.vue#L20-L23

**Comment by Onatcer** [comment]
thanks for the bug report! i fixed it now and deployed it on solidtime cloud. it will be included in the next community self-hosting release as well.
