### ISSUE TITLE
bug: phantom timer starts when entering start time manually

### ISSUE THREAD

**Issue by mertyn** [solidtime-io/solidtime#193]
sometimes i forget to start a timer when working on my projects. then i just put in the time i approximately started and immediately stop it when im done working. for some reason, sometimes there apparently is a timer started that isn’t visible in the app. when that happens, i receive an email notification, sometime way later, saying that there is a timer, that’s been running for a long time. when i then open the app again, there is a timer running that i can stop, but never started myself.

of course, when trying to reproduce this, it didn’t happen again, so there might be more circumstances causing this to happen. maybe it has something to do with closing the tab shortly after aswell?

i am using the official instance hosted on solidtime.io

**Comment by Onatcer** [comment]
hi, thanks for the report. 

yes i had this happen to me too. there is a potential fix for this in https://github.com/solidtime-io/solidtime/commit/8b50f33cc9a3153cebca26902a382bf17e9b6c28 but I'm not sure if this actually caused the phantom timer. 

feel free to send me your account either via email gregor@solidtime.io or via the chat bubble on app.solidtime.io, so i can look into your case as well.

**Comment by Onatcer** [comment]
Ok so i found a bug where a second timer could start when Tabbing through the Time Dropdown inside the TimeTracker. https://github.com/solidtime-io/solidtime/commit/b3b84db004c6cf99e0bcd27a4640767069e04ef3 

This sounds a lot like the issue you experienced. It will be deployed the next few days.

**Comment by mertyn** [comment]
might take some time until i can actually see if it's gone, but sounds good so far :)

**Comment by Onatcer** [comment]
I did not experience any such behavior recently so i think it is fixed. If you experience the issue again please feel free to comment below or open a new issue.
