### ISSUE TITLE
Adding tag to a group of times needs to be done twice, in order to be saved

### ISSUE THREAD

**Issue by FluffyDiscord** [solidtime-io/solidtime#202]
Adding tag to existing times at /time page to a group (time entries with same day within a day), I need to select the tag twice, in order to save to all entries (in my case two entries for that day)

**Comment by Onatcer** [comment]
@FluffyDiscord thank you for the report. There was a problem with refreshing the time entries after the update. 

The fix is now deployed, if you still experience the issue, feel free to comment below.
