### ISSUE TITLE
APP_FORCE_HTTPS=false not working

### ISSUE THREAD

**Issue by John-H-Smith** [solidtime-io/solidtime#209]
Hi, while trying to run a local-only setup (no reverse proxy), I set APP_FORCE_HTTPS in laravel.env to false.
But some files seem to still get requested over https:
![image](https://github.com/user-attachments/assets/9fe4a339-9dee-459b-b52c-01f6761216c5)
Also, the APP_URL is set to http://localhost

**Comment by timmitech** [comment]
Hey, I've got the same issue. I've tried "false" for APP_FORCE_HTTPS, I've tried commenting out. Unfortunately nothing works. Even if i turn it on and to open the login page via my internal reverse proxy i get redirected to my IP with https://. Doesn't matter what i configure in my nginx config file.

**Comment by micalm** [comment]
Looks like https will always be forced when the app is in production - https://github.com/solidtime-io/solidtime/blob/main/app/Providers/AppServiceProvider.php#L94.

Obvious hotfix is to remove ` || App::isProduction()`.

**Comment by timmitech** [comment]
I just changed the "production" to "dev" (couldn't find anythin else in the documentation) and now i get a login page. But  I can't login. With the "Register here" button i get to the sheet to register but it won't save my settings. Is there anything i am missing?

**Comment by Onatcer** [comment]
How are you running the application right now? Do you use the solidtime/solidtime docker image from docker hub? Or do you use the docker-compose.yml from the main repo? 

There are setup examples for self-hosting here, but they are currently: 
https://github.com/solidtime-io/self-hosting-examples

We removed the local setup instructions for development temporarily as people tried to setup solidtime with those instructions, which is not intended. The docker-compose.yml in this repository is not meant for production use. 

There is currently a bugfix branch for Force HTTPS config here: https://github.com/solidtime-io/solidtime/pull/207/files
I'm not sure if this is the same issue tho. I think the branch adresses an issue with some reverse proxy configurations.

**Comment by korridor** [comment]
I'll work on enabling a non-HTTPS setup tomorrow and add an example for that.

**Comment by korridor** [comment]
I just pushed a fix into the `main` image tag and updated the documentation (https://docs.solidtime.io/self-hosting/configuration#general).

Please check if this works for you now and the I'll release a new version so that this can be used in the `latest` image tag as well.

**Comment by korridor** [comment]
@timmitech

1. If you have a different issue, please create a new GitHub issue or write in the Discord channel for self-hosting. Also please provide more information about your setup; at least which example of the two you used, if you already said you used it.
3. Regarding your wish for the future: Using a nginx reverse proxy that handles HTTPS infront of solidtime is already possible. Not only is it possible we have a whole example exactly for that setup. [Docs](https://docs.solidtime.io/self-hosting/guides/docker#1-choose-the-example-that-fits-your-needs-the-best), Number 1 in the [example GitHub repo](https://github.com/solidtime-io/self-hosting-examples/tree/main/1-docker-with-database) Also the problem discussed in this GitHub issue would not be an issue for that setup.

**Comment by timmitech** [comment]
@korridor thank you for your effort! I tried a new installation with the main tag and it looks like it works. I changed the "APP_ENV" variable back to "production" and "APP_FORCE_HTTPS" to false and i can enter the page without being redirected to https://..
But unfortunately my database is still empty after creating the containers and starting the migration. As i already said - I can enter the login page, but cant register a user.

To at least provide the information: I used setup Number 1 (docker-with-database).

Since I wanted to use solidtime only for testing purposes it looks like it isn't really a project for me right now. Maybe I'll give it another try and open another issue in the futere when i have a little more spare time.

**Comment by korridor** [comment]
@timmitech Ok thanks, given the information, I would guess that you forgot to run the migrations. Here is the documentation about that: https://docs.solidtime.io/self-hosting/guides/docker#5-migrate-database

If this does not work, just write again and I can tell you what additional information I need.
