### ISSUE TITLE
Error “This action is unauthorized” when inviting a member to my organization

### ISSUE THREAD

**Issue by arnaudbagnis** [solidtime-io/solidtime#214]
Hello,

I’m experiencing an issue when trying to invite a member to my organization. The invited person receives the email notification successfully, but I receive an error message stating: “This action is unauthorized.”

	•	I have the necessary permissions to invite members.
	•	The error occurs regardless of the browser or device used.
	•	I’ve tried logging out and back in, but the issue persists.

**Comment by Onatcer** [comment]
Do you experience this issue in the a self-hosted version or on solidtime.io? Is the invited person able to join via the email notification regardless of the error message or does that not work in the end? 

If you are using the self-hosted version, can you please provide the version you are running.

**Comment by korridor** [comment]
@arnaudbagnis We are closing this issue for now. If you still have that issue, just comment here and we'll reopen it.
