### ISSUE TITLE
Last seven days section stays at 0h00min

### ISSUE THREAD

**Issue by MaelImhof** [solidtime-io/solidtime#218]
Hi !

I think the best way for me to describe the issue is through an image :

<img src="https://github.com/user-attachments/assets/976c9c81-b420-499e-a5a7-f88491aa445b" width="500" />

Today is Wednesday as I write the issue, so the three days with `0h00min` in `Last 7 Days` are Monday, Tuesday and Wednesday.

- The `This Week` section is updated properly
- The `Activity Graph` section is updated properly
- The `Last 7 Days` section **is not updated** and stays at `0h00min`

As you can tell, I've had this problem for three days now. Thought I'd open an issue before the seven days are at `0h00min`, so the issue is more visible.

### What I've tried

I've tried :
- Logging out and logging back in
- Clearing the website's data
- Clearing the browser's cache
- Logging in from another browser (I originally use Firefox, tried logging in in a vanilla installation of Edge)
- Tried disabling Firefox protection (it can sometimes block cookies or scripts)
- Tried disabling the `Privacy Badger` Firefox extension (it can sometimes block cookies or scripts)

The issue remains.

### Environment information

- Firefox 132.0 (64-bit)
- Privacy Badger installed and blocking ` o4507102829543424.ingest.de.sentry.io`, but disabling the extension does not help

I don't feel like it is a terribly important issue, I can live with it, but I thought I'd still report it in case it's not just me and there's an actual underlying problem. And if there's a way to fix it then nice.

Cheers !

**Comment by Onatcer** [comment]
thanks for the report, i was able to reproduce it, we'll look into it and give an update once it is fixed.

**Comment by korridor** [comment]
Thanks for the report! The issue should be resolved now with commit https://github.com/solidtime-io/solidtime/commit/f4cfeaa71858a5224111ae09b224011dd0c8f0e6

The bug had something to do with daylight saving time, which was a few days ago central Europe.

**Comment by MaelImhof** [comment]
Oh wow did not figure out the relation, but yes I changed hours on Sunday.

Thank you very much for the quick fix ! It works now 👌🏻
