### ISSUE TITLE
Project Time Estimated don't save. 

### ISSUE THREAD

**Issue by mikaelosterberg** [solidtime-io/solidtime#224]
Can't get Time Estimated to save to database. 
Not om Project creation or update. 
estimated_time is set in the update request.

Running tag 0.3.1from git.

**Comment by korridor** [comment]
@mikaelosterberg This should now be fixed in the `main` Docker image. It will also be available in the `latest` tag after the next release.

**Comment by korridor** [comment]
PR: https://github.com/solidtime-io/solidtime/pull/226

**Comment by korridor** [comment]
A fix is released now: https://github.com/solidtime-io/solidtime/releases/tag/v0.4.0

**Comment by whysthatso** [comment]
@korridor are you seeing this?

**Comment by korridor** [comment]
@whysthatso Sorry for the late response. Are you sure that you ran the migrations after the upgrade?

See this section in the documentation for more information about running the migrations: https://docs.solidtime.io/self-hosting/guides/docker#5-migrate-database

**Comment by whysthatso** [comment]
d'Oh. yeah, sorry. nevermind then. i somehow assumed they checked and run upon application boot.

**Comment by korridor** [comment]
@whysthatso I understand it might be a bit confusing. The solidtime container only does that if you set `AUTO_DB_MIGRATE` to `true`.
