### ISSUE TITLE
Can't select mulit tags

### ISSUE THREAD

**Issue by dwdcth** [solidtime-io/solidtime#227]
Hi, as shown in the GIF, selecting a single tag displays normally, but when multiple tags are selected, the bar chart disappears.
![tag](https://github.com/user-attachments/assets/1eb34ab1-e9f5-4c92-8afe-8c3c532a9423)

**Comment by korridor** [comment]
@dwdcth Thanks for the report. You are right this is a bug. This filter should be an OR, but it is currently implemented as an AND by mistake.

We'll fix that as soon as possible! :)

**Comment by korridor** [comment]
PR: https://github.com/solidtime-io/solidtime/pull/228

**Comment by korridor** [comment]
@dwdcth This should be fixed now and is deployed on solidtime cloud. You can try out the fix by using the `main` docker image tag. After the next release the fix will be available in the `latest` tag as well.
