### ISSUE TITLE
Hide project from Employee if not Project Members

### ISSUE THREAD

**Issue by mikaelosterberg** [solidtime-io/solidtime#264]
Wood like a toggle or a default that hide all projects from employee level users and only show if the user is a Project Members.

**Comment by korridor** [comment]
Employees should already only see the projects that they are assigned to. Could you please check again if that is the case? And if not please provide further information for us to reproduce that.

**Comment by mikaelosterberg** [comment]
Looks like the user had multiple entrys in project_members. When removes stuff cleard up.
