### ISSUE TITLE
Website: Missing CSS Resources

### ISSUE THREAD

**Issue by nhalstead** [solidtime-io/solidtime#275]
https://www.solidtime.io/

It looks like the website is showing a 404 page for "https://www.solidtime.io/_astro/imprint.BF1m9DaP.css"

![image](https://github.com/user-attachments/assets/f78db450-33c6-48c4-b0a9-f83e944d5208)

**Comment by korridor** [comment]
@nhalstead Thanks for the report, might have been a caching error after a deployment. Could you do a full reload and see if the problem persists?

If it does persist please provide us with the value of the `server` and the `cdn-*` headers from the main HTML request on `/`.

**Comment by markus-ruderman** [comment]
Seems to be fixed:

![image](https://github.com/user-attachments/assets/f653a992-6321-4778-990d-0501e2f6fca3)
