### ISSUE TITLE
Import is already in progress after Error

### ISSUE THREAD

**Issue by Zarpyk** [solidtime-io/solidtime#293]
After import error (Invalid CSV header, missing field: "..." #294 ) I need to restart the docker to try another import

![imagen](https://github.com/user-attachments/assets/38097a60-8274-4c5f-b074-3401c31057f8)

**Comment by korridor** [comment]
Thanks for the report! Did you try this in solidtime Cloud or on a self-hosted instance?

**Comment by Zarpyk** [comment]
With self-hosted
This is the log: [_solidtime-app_logs.txt](https://github.com/user-attachments/files/18184231/_solidtime-app_logs.txt)
The import csv: [Clockify_Proyecto_export_12_18_2024.csv](https://github.com/user-attachments/files/18184241/Clockify_Proyecto_export_12_18_2024.csv)

**Comment by korridor** [comment]
Thanks we'll look into that!
