### ISSUE TITLE
Recently Tracked Tasks don't show any task

### ISSUE THREAD

**Issue by Zarpyk** [solidtime-io/solidtime#305]
The space of Recently Tracked Tasks don't show any task on cloud and self-host.

Cloud screenshots:
![imagen](https://github.com/user-attachments/assets/82b004dc-c7c1-49a2-952f-15b4e6b1fa22)
![imagen](https://github.com/user-attachments/assets/9aff2b89-1f08-4dc1-9721-c74125e9d987)

**Comment by Onatcer** [comment]
Tasks will only show up in the "Recently Tracked Tasks" Section on the Dashboard after you have created a time entry with them.
